name: Deploy to GitHub Pages

on:
  workflow_dispatch:    # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build site
        run: |
          # put your build steps here
          echo "Building site..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: .   # directory with your built site
